apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    tier: frontend
  annotations:
    kubernetes.io/change-cause: nginx image updated to 1.7.9  
spec:
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
  replicas: 4
  selector:
    matchLabels:
      app: web
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1


