apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    tier: frontend
  annotations:
    kubernetes.io/change-cause: nginx image updated to 1.8.1
spec:
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.8.1
  replicas: 4
  selector:
    matchLabels:
      app: web
      tier: frontend
