apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
  labels:
    tier: frontend
spec:
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: web
      tier: frontend
